---
- name: install ssl cert and key from local to shellrelay
  hosts: shellrelay
  become: yes
    
  tasks:

   - synchronize:
       src: ./tmp/
       dest: /etc/letsencrypt/
   
   - name: reload nginx
     ansible.builtin.service:
       name: nginx
       state: reloaded     
     
