---
- name: download ssl cert and key from session relay to local 
  hosts: sessionrelay
  become: yes
    
  tasks:

   - synchronize:
       mode: pull
       src: /etc/letsencrypt/
       dest: ./tmp/
